spring:
  datasource:
    url: jdbc:postgresql://db:5432/taskdb
    username: task
    password: task

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration